# Use an official Python runtime as a parent image
FROM python:3.11.4

# Set the working directory in the container
WORKDIR /load_balancer

# Copy the current directory contents into the container at /app
COPY . /load_balancer

# Install any needed dependencies specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run loadbalancer.py when the container launches
CMD ["python", "load_balancer.py"]